create or replace PROCEDURE ELIMINAR_CLIENTE_POR_DNI(v_Dni IN Clientes.Dni%TYPE)
IS
BEGIN
    DELETE FROM Clientes WHERE Dni = v_Dni;
    COMMIT;
END ELIMINAR_CLIENTE_POR_DNI;
/

create or replace PROCEDURE ELIMINAR_GESTOR(
v_OIDTrabajador IN veterinarios.oidtrabajador%TYPE)
 IS 
BEGIN
DELETE FROM Gestores WHERE oidtrabajador = v_oidtrabajador;
DELETE FROM Trabajadores WHERE oidtrabajador = v_oidtrabajador;

    COMMIT;
END ELIMINAR_GESTOR;
/
create or replace PROCEDURE ELIMINAR_CITA_POR_OIDTRABAJADOR (v_OIDTrabajador IN Citas.OIDTrabajador%TYPE)
IS
BEGIN
    DELETE FROM CITAS WHERE OIDTrabajador = v_OIDTrabajador;
   

    COMMIT;
END ELIMINAR_CITA_POR_OIDTRABAJADOR;
/
create or replace PROCEDURE ELIMINAR_CITA (v_OIDCITA IN CITAS.OIDCITA%TYPE)
IS
BEGIN

    DELETE FROM CITAS WHERE OIDCITA= v_OIDCITA;
   

    COMMIT;
END ELIMINAR_CITA;
/
create or replace PROCEDURE ELIMINAR_PETCITA (v_OIDPETCITA IN PETICIONCITAS.OIDPETCITA%TYPE)
IS
BEGIN
    DELETE FROM PETICIONCITAS WHERE OIDPETCITA = v_OIDPETCITA;

    COMMIT;
END ELIMINAR_PETCITA;
/
create or replace PROCEDURE ELIMINAR_TRABAJADOR(
v_OIDTrabajador IN trabajadores.oidtrabajador%TYPE)
 IS 
BEGIN
    DELETE FROM Trabajadores WHERE oidtrabajador = v_oidtrabajador;
    COMMIT;
END ELIMINAR_TRABAJADOR;
/