create or replace PROCEDURE ELIMINAR_CITA_POR_OIDTRABAJADOR (v_OIDTrabajador IN Citas.OIDTrabajador%TYPE)
IS
BEGIN
    DELETE FROM CITAS WHERE OIDTrabajador = v_OIDTrabajador;
   

    COMMIT;
END ELIMINAR_CITA_POR_OIDTRABAJADOR;
