create or replace PROCEDURE ELIMINAR_PETCITA (v_OIDPETCITA IN PETICIONCITAS.OIDPETCITA%TYPE)
IS
BEGIN
    DELETE FROM PETICIONCITAS WHERE OIDPETCITA = v_OIDPETCITA;

    COMMIT;
END ELIMINAR_PETCITA;
