create or replace PROCEDURE ELIMINAR_CONSULTA_POR_CITA (v_OIDCitas IN Citas.OIDCita%TYPE)
IS
BEGIN
    DELETE FROM Consultas WHERE OIDCita = v_OIDCitas;
    DELETE FROM CITAS WHERE OIDCita = v_OIDCitas;

    COMMIT;
END ELIMINAR_CONSULTA_POR_CITA;
