create or replace PROCEDURE ELIMINAR_PELUQUERIA_POR_CITA (v_OIDCitas IN Citas.OIDCita%TYPE)
IS
BEGIN
    DELETE FROM Peluquerias WHERE OIDCita = v_OIDCitas;
    DELETE FROM citas WHERE OIDCita = v_OIDCitas;

    COMMIT;
END ELIMINAR_PELUQUERIA_POR_CITA;
