
create or replace PROCEDURE MODIFICAR_CLIENTE
(EMAIL_v IN CLIENTES.EMAIL%TYPE,
NUMEROTELEFONO_v IN CLIENTES.NUMEROTELEFONO%TYPE,
 NOMBRE_v IN CLIENTES.NOMBRE%TYPE,
 APELLIDOS_v IN CLIENTES.APELLIDOS%TYPE,
 DIRECCION_v IN CLIENTES.DIRECCION%TYPE,
 PASS_v IN CLIENTES.PASS%TYPE) IS
BEGIN
  UPDATE CLIENTES
  SET NUMEROTELEFONO = NUMEROTELEFONO_v, NOMBRE=NOMBRE_v, APELLIDOS=APELLIDOS_v, 
	DIRECCION=DIRECCION_v,  PASS = PASS_v
  WHERE EMAIL = EMAIL_v;
END;